/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import CasContract.Leaf
public import LeanCategories.Catalogue.Semantics.Algebra.Subgroups
public import CasLeaves.Algebra.Subgroups
public meta import CasContract.Leaf

@[expose] public section

/-!
# Decoding a backend's kernel (CC-DECODE)

A backend answers "the kernel of `f : G → H`" as

```text
BackendResult { operation := "lim.groups.kernel",
                encoded := {"subgroup": {...}, "inclusion": [...]} }
```

and the adapter decodes it into the operation's semantic result type — a subgroup of `G`, i.e. a
monomorphism `K ↪ G` (`SubgroupHandle`) — or rejects it. It never trusts the backend's shape: it
rebuilds the table of `K` and checks its laws, checks that the inclusion is an injective
homomorphism into `G`, and checks exactness: the image is exactly `{x | f x = 1}`
(`MonoidHom.ker`). A result without its inclusion is not a kernel and is rejected.

`nativeKernel` is the Lean-native realization, for comparison.
-/

open Lean
open CasCatalogue.Algebra.Actions CasCatalogue.Algebra.Subgroups

namespace CasCatalogue.Algebra.KernelDecode

/-- A result crossing the backend boundary: the semantic operation it answers, and its encoding. -/
structure BackendResult where
  operation : String
  encoded : Json

/-- The registered semantic operation this decoder serves: the kernel of groups. -/
def kernelOperation : String := "lim.groups.kernel"

/-- The kernel elements of a table homomorphism. -/
def kernelElements (f : HomHandle) : List (Fin f.source.size) :=
  (List.finRange f.source.size).filter fun x => f.map x = f.target.one

/-- The Lean-native kernel: the subgroup generated by the kernel elements (which it is). -/
def nativeKernel (f : HomHandle) : Option SubgroupHandle :=
  decode { ambient := f.source, generators := kernelElements f, claimsAbelian := false
           methodNames := [] }

/-- Read an index `< n` from JSON. -/
def readFin (n : ℕ) (j : Json) : Except String (Fin n) := do
  let k ← j.getNat?
  if h : k < n then pure ⟨k, h⟩ else throw s!"index {k} out of range {n}"

/-- Read a function `Fin k → Fin n` given as a JSON array. -/
def readFun (k n : ℕ) (j : Json) : Except String (Fin k → Fin n) := do
  let arr ← j.getArr?
  unless arr.size == k do throw s!"expected {k} entries, got {arr.size}"
  let values ← arr.mapM (readFin n)
  if h : values.size = k then pure fun i => values[i.val]'(h ▸ i.isLt)
  else throw "size mismatch"

/-- Read a table `Fin k → Fin k → Fin k` given as a JSON array of rows. -/
def readTable (k : ℕ) (j : Json) : Except String (Fin k → Fin k → Fin k) := do
  let rows ← j.getArr?
  unless rows.size == k do throw s!"expected {k} rows, got {rows.size}"
  let parsed ← rows.mapM (readFun k k)
  if h : parsed.size = k then pure fun i => parsed[i.val]'(by rw [h]; exact i.isLt)
  else throw "size mismatch"

/-- A proof of the decidable `p`, or the rejection `message`. -/
def require (p : Prop) [Decidable p] (message : String) : Except String (PLift p) :=
  if h : p then pure ⟨h⟩ else throw message

/-- Decode a backend's kernel of `f` into the semantic subgroup `K ↪ dom f`, or reject it. -/
def decodeKernel (f : HomHandle) (result : BackendResult) : Except String SubgroupHandle := do
  unless result.operation == kernelOperation do
    throw s!"result answers {result.operation}, not {kernelOperation}"
  let subgroup ← result.encoded.getObjVal? "subgroup"
  let some inclusionJson := (result.encoded.getObjVal? "inclusion").toOption
    | throw "the backend's kernel is missing its defining arrow, the inclusion K ↪ G: \
        it is not a kernel"
  let k ← subgroup.getObjValAs? Nat "size"
  let mul ← readTable k (← subgroup.getObjVal? "mul")
  let one ← readFin k (← subgroup.getObjVal? "one")
  let inv ← readFun k k (← subgroup.getObjVal? "inv")
  let G := f.source
  let map ← readFun k G.size inclusionJson
  let ⟨assoc⟩ ← require (∀ a b c, mul (mul a b) c = mul a (mul b c))
    "the backend's subgroup table is not associative"
  let ⟨one_mul⟩ ← require (∀ a, mul one a = a) "the backend's unit is not a left unit"
  let ⟨mul_one⟩ ← require (∀ a, mul a one = a) "the backend's unit is not a right unit"
  let ⟨inv_mul⟩ ← require (∀ a, mul (inv a) a = one) "the backend's inverses are not inverses"
  let source : GroupTable := { size := k, mul, assoc, one, one_mul, mul_one, inv, inv_mul }
  let ⟨map_mul⟩ ← require (∀ a b, map (source.mul a b) = G.mul (map a) (map b))
    "the backend's inclusion is not a homomorphism"
  let ⟨injective⟩ ← require (∀ a b : Fin k, map a = map b → a = b)
    "the backend's inclusion is not injective"
  unless (List.finRange k).all fun a => f.map (map a) = f.target.one do
    throw "the backend's subgroup is not contained in the kernel"
  unless (kernelElements f).all fun x => (List.finRange k).any fun a => map a = x do
    throw "the backend's subgroup misses kernel elements"
  pure { source, target := G, map, map_mul, injective }

/-- Encode a subgroup handle as a backend would send it (for round-trip tests). -/
def encodeKernel (h : SubgroupHandle) : BackendResult :=
  let k := h.source.size
  let idx {n : ℕ} (x : Fin n) : Json := toJson x.val
  { operation := kernelOperation
    encoded := Json.mkObj [
      ("subgroup", Json.mkObj [
        ("size", toJson k),
        ("mul", Json.arr ((List.finRange k).map fun a =>
          Json.arr ((List.finRange k).map fun b => idx (h.source.mul a b)).toArray).toArray),
        ("one", idx h.source.one),
        ("inv", Json.arr ((List.finRange k).map fun a => idx (h.source.inv a)).toArray)]),
      ("inclusion", Json.arr ((List.finRange k).map fun a => idx (h.map a)).toArray)] }

end CasCatalogue.Algebra.KernelDecode
