/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import CasContract.Leaf
public import CasLeaves.Algebra.Actions
public import LeanCategories.Catalogue.Semantics.ConstructorRegistration
public import Mathlib.Algebra.Category.Grp.EpiMono
public import Mathlib.CategoryTheory.Subobject.Lattice
public import Mathlib.Algebra.Category.Grp.Limits
public import LeanCategories.Catalogue.Semantics.Algebra.Subgroups
public meta import CasContract.Leaf
public meta import LeanCategories.Catalogue.Semantics.ConstructorCatalogue
public meta import LeanCategories.Catalogue.Semantics.Algebra.Catalogue.Magmas
public meta import LeanCategories.Catalogue.Semantics.Algebra.Subgroups

@[expose] public section

/-!
# Lean-native realizations for `LeanCategories.Catalogue.Semantics.Algebra.Subgroups`

The leaf half of `LeanCategories.Catalogue.Semantics.Algebra.Subgroups`: handles, their denotations and the actions of the registered functors on
them, contributed through `register_leaf`.
-/

open CategoryTheory
open LeanCategories LeanCategories.Algebra CasCatalogue.Algebra.Actions

namespace CasCatalogue

namespace Algebra.Subgroups

universe u

/-! ### Realizations: homomorphisms and embeddings of group tables -/

/-- A homomorphism of group tables. -/
structure HomHandle where
  source : GroupTable
  target : GroupTable
  map : Fin source.size → Fin target.size
  map_mul : ∀ a b, map (source.mul a b) = target.mul (map a) (map b)

/-- The monoid homomorphism a table homomorphism denotes. -/
def HomHandle.hom (h : HomHandle) : h.source.Carrier →* h.target.Carrier :=
  MonoidHom.mk' (M := h.source.Carrier) (G := h.target.Carrier) h.map h.map_mul

/-- An injective homomorphism of group tables: a realization of a subgroup of its target. -/
structure SubgroupHandle extends HomHandle where
  injective : ∀ a b, map a = map b → a = b

/-- Homomorphisms of group tables, with identities only (`Discrete`), denoting arrows of groups. -/
noncomputable def arrowDenotation : Discrete HomHandle ⥤ arrowsGroupsCategory.{0} :=
  Discrete.functor fun h => Arrow.mk (GrpCat.ofHom h.hom)

theorem SubgroupHandle.mono (h : SubgroupHandle) :
    Mono (GrpCat.ofHom h.toHomHandle.hom) :=
  (GrpCat.mono_iff_injective _).mpr fun a b e => h.injective a b e

/-- A subgroup handle denotes the subobject `H ↪ G`: the monomorphism, not just `H`. -/
noncomputable def subgroupDenotation : Discrete SubgroupHandle ⥤ subobjectsGroupsCategory.{0} :=
  Discrete.functor fun h => ⟨Arrow.mk (GrpCat.ofHom h.toHomHandle.hom), h.mono⟩

/-- The domain action: a subgroup is its own group table. -/
noncomputable def domainAction :
    RealizedAction domainDeclaration.{0} subgroupDenotation groupDenotation :=
  RealizedAction.discrete _ (fun h => h.source) fun _ => rfl

/-- The inclusion action: the retained embedding, as an arrow. -/
noncomputable def inclusionAction :
    RealizedAction inclusionDeclaration.{0} subgroupDenotation arrowDenotation :=
  RealizedAction.discrete _ (fun h => ⟨h.toHomHandle⟩) fun _ => rfl

/-! ### Decoding a hostile backend subgroup -/

/-- What a messy backend hands back for "the subgroup generated by these elements": generators
that are not closed, a label it asserts, and its method inventory. -/
structure HostileSubgroup where
  ambient : GroupTable
  generators : List (Fin ambient.size)
  claimsAbelian : Bool
  methodNames : List String

/-- One closure step: products, inverses. -/
def closureStep (G : GroupTable) (xs : List (Fin G.size)) : List (Fin G.size) :=
  (xs ++ xs.flatMap (fun a => xs.map (G.mul a)) ++ xs.map G.inv).dedup

/-- The subgroup generated by `gens`, as a list (closed after `G.size` steps). -/
def closure (G : GroupTable) (gens : List (Fin G.size)) : List (Fin G.size) :=
  (List.range G.size).foldl (fun xs _ => closureStep G xs) (G.one :: gens).dedup

/-- Re-index a list of elements of `G` as a table on `Fin k`. -/
def reindex (G : GroupTable) (members : List (Fin G.size)) (hk : 0 < members.length)
    (x : Fin G.size) : Fin members.length :=
  ⟨members.idxOf x % members.length, Nat.mod_lt _ hk⟩

/-- Decode a hostile backend subgroup into a subgroup realization: compute the generated
subgroup, its table and its embedding, and check every law. Only the generators are read; the
backend's label and methods are ignored. Fails (returns `none`) if any law fails. -/
def decode (h : HostileSubgroup) : Option SubgroupHandle :=
  let G := h.ambient
  let members := closure G h.generators
  if hk : 0 < members.length then
    let idx := reindex G members hk
    let elt : Fin members.length → Fin G.size := fun i => members.get i
    let mul : Fin members.length → Fin members.length → Fin members.length :=
      fun i j => idx (G.mul (elt i) (elt j))
    let one := idx G.one
    let inv := fun i => idx (G.inv (elt i))
    if assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c) then
    if one_mul : ∀ a, mul one a = a then
    if mul_one : ∀ a, mul a one = a then
    if inv_mul : ∀ a, mul (inv a) a = one then
    if map_mul : ∀ a b, elt (mul a b) = G.mul (elt a) (elt b) then
    if injective : ∀ a b, elt a = elt b → a = b then
      some { source := { size := members.length, mul, assoc, one, one_mul, mul_one, inv, inv_mul }
             target := G, map := elt, map_mul, injective }
    else none else none else none else none else none else none
  else none

end Algebra.Subgroups

open Algebra.Subgroups

register_leaf
  { backend := "lean"
    contributions := [
  .action
  { id := ⟨"act.subobjects_groups.domain.table"⟩, edge := .functor FunctorId.subobjectsGroupsDomain
    realization := `CasCatalogue.Algebra.Subgroups.domainAction },
  .action
  { id := ⟨"act.subobjects_groups.inclusion.table"⟩
    edge := .functor FunctorId.subobjectsGroupsInclusion
    realization := `CasCatalogue.Algebra.Subgroups.inclusionAction },
  .realizer
  { id := ⟨"rz.subobjects_groups.table"⟩, category := ⟨"cat.subobjects_groups"⟩, backend := "lean"
    denotation := `CasCatalogue.Algebra.Subgroups.subgroupDenotation },
  .realizer
  { id := ⟨"rz.arrows_groups.table"⟩, category := ⟨"cat.arrows_groups"⟩, backend := "lean"
    denotation := `CasCatalogue.Algebra.Subgroups.arrowDenotation }] }

end CasCatalogue
